- name: Create Ansible workspace
  file: path={{ ansible_workspace }} state=directory
  tags: [create_workspace]

- name: Archive & get backup from repo files in /etc/yum.repos.d/
  archive: path=/etc/yum.repos.d/* dest=/etc/yum.repos.d/oldrepo.gz remove=yes
  tags: [archive_backup]

- name: Unarchive localrepo
  unarchive: src=localrepo.gz dest={{ ansible_workspace }} copy=yes
  tags: [unarchive_localrepo]

- name: Copy localrepo.repo to /etc/yum.repos.d/
  copy: src=localrepo.repo dest=/etc/yum.repos.d
  tags: [copy_localrepo]

- name: Install nfs-utils
  yum: name=nfs-utils state=present
  tags: [Install_NFS]

- name: Create share directory
  file: path={{ share_directory_path }} state=directory
  tags: [create_share]

- name: Mount nfs directory
  shell: mount -t nfs {{ NFS_SERVER_IP }}:{{ share_directory_path }}  {{ share_directory_path_client }}
  tags: [mount_nfs]

- name: Set to /etc/fstab
  mount:
    src: "{{ NFS_SERVER_IP }}":"{{ share_directory_path_server }}" 
    path: "{{ share_directory_path_client }}" 
    fstype: nfs
    opts: defaults
    dump: 0
    passno: 0
    state: mounted
    backup: yes
  tags: [fstab]

- name: Remove ansible workspace
  file: path={{ ansible_workspace }} state=absent 
  tags: [remove_workspace]

- name: Run df -h
  shell: df -h
  register: df_result
  tags: [df]

- name: Show df -h content
  debug: msg={{ df_result }}
  tags: [df]

- name: cat /etc/fstab 
  shell: cat /etc/fstab
  register: fstab_result
  tags: [fstab_show]

- name: Show /etc/fstab content
  debug: msg={{ fstab_result }}
  tags: [fstab_show]
