- name: client|Create Ansible workspace
  file: path={{ ansible_workspace }} state=directory
  tags: [create_workspace]

- name: client|Archive & get backup from repo files in /etc/yum.repos.d/
  archive: path=/etc/yum.repos.d/* dest=/etc/yum.repos.d/oldrepo.gz remove=yes
  tags: [archive_backup]

- name: client|Unarchive localrepo
  unarchive: src=localrepo.gz dest={{ ansible_workspace }} copy=yes
  tags: [unarchive_localrepo]

- name: client|Copy localrepo.repo to /etc/yum.repos.d/
  copy: src=localrepo.repo dest=/etc/yum.repos.d
  tags: [copy_localrepo]

- name: client|Install nfs-utils
  yum: name=nfs-utils state=present
  tags: [Install_NFS]

- name: client|Create share directory
  file: path={{ share_directory_path_client }} state=directory
  tags: [create_share_client]

- name: client|Mount nfs directory
  shell: mount -t nfs {{ NFS_SERVER_IP }}:{{ share_directory_path_server }}  {{ share_directory_path_client }}
  tags: [mount_nfs]

- name: client|Set to /etc/fstab
  mount:
    src: "{{ NFS_SERVER_IP }}:{{ share_directory_path_server }}"
    path: "{{ share_directory_path_client }}" 
    fstype: nfs
    opts: defaults
    dump: 0
    passno: 0
    state: mounted
    backup: yes
  tags: [fstab]

- name: client|Remove ansible workspace
  file: path={{ ansible_workspace }} state=absent 
  tags: [remove_workspace]

- name: client|Run df -h
  shell: df -h
  register: df_result
  tags: [df]

- name: client|Show df -h content
  debug: msg={{ df_result }}
  tags: [df]

- name: client|cat /etc/fstab 
  shell: cat /etc/fstab
  register: fstab_result
  tags: [fstab_show]

- name: client|Show /etc/fstab content
  debug: msg={{ fstab_result }}
  tags: [fstab_show]
